export const CALCULATOR = [{
  label: 'MR',
  style: 'memory',
  callback: 'showMemory'
}, {
  label: 'MC',
  style: 'memory',
  callback: 'clearMemory'
}, {
  label: 'M+',
  style: 'memory',
  callback: 'addMemory'
}, {
  label: '(',
  style: 'symbol',
  callback: 'addExpression'
}, {
  label: ')',
  style: 'symbol',
  callback: 'addExpression'
}, {
  label: 7,
  style: 'number',
  callback: 'addExpression'
}, {
  label: 8,
  style: 'number',
  callback: 'addExpression'
}, {
  label: 9,
  style: 'number',
  callback: 'addExpression'
}, {
  label: '/',
  style: 'symbol',
  callback: 'addExpression'
}, {
  label: 'C',
  style: 'clear',
  callback: 'clearAll'
}, {
  label: 4,
  style: 'number',
  callback: 'addExpression'
}, {
  label: 5,
  style: 'number',
  callback: 'addExpression'
}, {
  label: 6,
  style: 'number',
  callback: 'addExpression'
}, {
  label: '×',
  style: 'symbol',
  value: '*',
  callback: 'addExpression'
}, {
  label: 'CE',
  style: 'clear',
  callback: 'delExpression'
}, {
  label: 1,
  style: 'number',
  callback: 'addExpression'
}, {
  label: 2,
  style: 'number',
  callback: 'addExpression'
}, {
  label: 3,
  style: 'number',
  callback: 'addExpression'
}, {
  label: '-',
  style: 'symbol',
  callback: 'addExpression'
}, {
  label: '√',
  style: 'symbol',
  callback: 'addExpression'
}, {
  label: '±',
  style: 'symbol',
  callback: 'plusMinus'
}, {
  label: 0,
  style: 'number',
  callback: 'addExpression'
}, {
  label: '.',
  style: 'number',
  callback: 'addExpression'
}, {
  label: '+',
  style: 'symbol',
  callback: 'addExpression'
}, {
  label: '=',
  style: 'memory',
  callback: 'equal'
}]
